INCFLAGS += -I$(CORE_DIR) -I$(CORE_DIR)/utils -I$(CORE_DIR)/helpers -I$(CORE_DIR)/include \
				-I$(CORE_DIR)/libretro-common/include

SOURCES_CXX  := $(CORE_DIR)/engine/mesh.cpp \
					 $(CORE_DIR)/engine/texture.cpp \
					 $(CORE_DIR)/engine/object.cpp \
					 $(CORE_DIR)/engine/shader.cpp \
					 $(CORE_DIR)/helpers/collision_detection.cpp \
					 $(CORE_DIR)/program/instancingviewer.cpp \
					 $(CORE_DIR)/program/modelviewer.cpp \
					 $(CORE_DIR)/libretro.cpp
SOURCES_C    := $(CORE_DIR)/utils/rpng.c \
					 $(CORE_DIR)/utils/picojpeg.c \
					 $(CORE_DIR)/helpers/location_math.c \
					 $(CORE_DIR)/utils/picojpeg-util.c \
					 $(CORE_DIR)/libretro-common/features/features_cpu.c \
					 $(CORE_DIR)/libretro-common/formats/image_texture.c \
					 $(CORE_DIR)/libretro-common/formats/image_transfer.c \
					 $(CORE_DIR)/libretro-common/formats/bmp/rbmp.c \
					 $(CORE_DIR)/libretro-common/formats/jpeg/rjpeg.c \
					 $(CORE_DIR)/libretro-common/formats/png/rpng.c \
					 $(CORE_DIR)/libretro-common/formats/tga/rtga.c \
					 $(CORE_DIR)/libretro-common/file/nbio/nbio_stdio.c \
					 $(CORE_DIR)/libretro-common/file/archive_file.c \
					 $(CORE_DIR)/libretro-common/file/archive_file_zlib.c \
					 $(CORE_DIR)/libretro-common/file/file_path.c \
					 $(CORE_DIR)/libretro-common/file/retro_stat.c \
					 $(CORE_DIR)/libretro-common/streams/file_stream.c \
					 $(CORE_DIR)/libretro-common/compat/compat_strl.c \
					 $(CORE_DIR)/libretro-common/compat/compat_posix_string.c \
					 $(CORE_DIR)/libretro-common/lists/string_list.c \
					 $(CORE_DIR)/libretro-common/gfx/math/vector_2.c \
					 $(CORE_DIR)/libretro-common/gfx/math/vector_3.c \
					 $(CORE_DIR)/libretro-common/glsym/rglgen.c

ifeq ($(GLES),1)
SOURCES_C    += $(CORE_DIR)/libretro-common/glsym/glsym_es2.c
else
SOURCES_C    += $(CORE_DIR)/libretro-common/glsym/glsym_gl.c
endif

SOURCES_CXX  += $(CORE_DIR)/utils/rtga.cpp
